### ISSUE TITLE
Incorrect code snippet in Chapter 2 under `Creating entity graph`

### ISSUE THREAD

**Issue by Ashvith10** [mikro-orm/guide#5]
While creating Article, it is missing a few parameters, without which it fails to apply the transaction.

**server.ts**
```diff
17,20c17,22
< const article = em.create(Article, {
<   title: 'Foo is Bar',
<   text: 'Lorem impsum dolor sit amet',
<   author: user.id,
---
> const article = em.create(Article, { 
>     slug: 'foo',
>     title: 'Foo', 
>     text: 'Lorem impsum dolor sit amet', 
>     description: 'Foo is Bar', 
>     author: user.id 
```

**Comment by B4nan** [comment]
PR welcome

**Comment by Ashvith10** [comment]
Added a PR in mikro-orm/mikro-orm#6299 with respect to the above topic. I've made some changes in the assigned value  to match with the console log at the end of the sub-topic "Creating entity graph".

**Comment by B4nan** [comment]
thanks
